require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LaborersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Laborer. As you add validations to Laborer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LaborersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all laborers as @laborers" do
      laborer = Laborer.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:laborers)).to eq([laborer])
    end
  end

  describe "GET #show" do
    it "assigns the requested laborer as @laborer" do
      laborer = Laborer.create! valid_attributes
      get :show, {:id => laborer.to_param}, valid_session
      expect(assigns(:laborer)).to eq(laborer)
    end
  end

  describe "GET #new" do
    it "assigns a new laborer as @laborer" do
      get :new, {}, valid_session
      expect(assigns(:laborer)).to be_a_new(Laborer)
    end
  end

  describe "GET #edit" do
    it "assigns the requested laborer as @laborer" do
      laborer = Laborer.create! valid_attributes
      get :edit, {:id => laborer.to_param}, valid_session
      expect(assigns(:laborer)).to eq(laborer)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Laborer" do
        expect {
          post :create, {:laborer => valid_attributes}, valid_session
        }.to change(Laborer, :count).by(1)
      end

      it "assigns a newly created laborer as @laborer" do
        post :create, {:laborer => valid_attributes}, valid_session
        expect(assigns(:laborer)).to be_a(Laborer)
        expect(assigns(:laborer)).to be_persisted
      end

      it "redirects to the created laborer" do
        post :create, {:laborer => valid_attributes}, valid_session
        expect(response).to redirect_to(Laborer.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved laborer as @laborer" do
        post :create, {:laborer => invalid_attributes}, valid_session
        expect(assigns(:laborer)).to be_a_new(Laborer)
      end

      it "re-renders the 'new' template" do
        post :create, {:laborer => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested laborer" do
        laborer = Laborer.create! valid_attributes
        put :update, {:id => laborer.to_param, :laborer => new_attributes}, valid_session
        laborer.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested laborer as @laborer" do
        laborer = Laborer.create! valid_attributes
        put :update, {:id => laborer.to_param, :laborer => valid_attributes}, valid_session
        expect(assigns(:laborer)).to eq(laborer)
      end

      it "redirects to the laborer" do
        laborer = Laborer.create! valid_attributes
        put :update, {:id => laborer.to_param, :laborer => valid_attributes}, valid_session
        expect(response).to redirect_to(laborer)
      end
    end

    context "with invalid params" do
      it "assigns the laborer as @laborer" do
        laborer = Laborer.create! valid_attributes
        put :update, {:id => laborer.to_param, :laborer => invalid_attributes}, valid_session
        expect(assigns(:laborer)).to eq(laborer)
      end

      it "re-renders the 'edit' template" do
        laborer = Laborer.create! valid_attributes
        put :update, {:id => laborer.to_param, :laborer => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested laborer" do
      laborer = Laborer.create! valid_attributes
      expect {
        delete :destroy, {:id => laborer.to_param}, valid_session
      }.to change(Laborer, :count).by(-1)
    end

    it "redirects to the laborers list" do
      laborer = Laborer.create! valid_attributes
      delete :destroy, {:id => laborer.to_param}, valid_session
      expect(response).to redirect_to(laborers_url)
    end
  end

end
